package com.securejobs.domain;
// Generated Feb 7, 2014 3:34:15 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * EducationLevels generated by hbm2java
 */
public class EducationLevels  implements java.io.Serializable {


     private Short idEducationLevel;
     private String educationLevel;
     private Set<Persons> personses = new HashSet<Persons>(0);
     private Set<EducationalQualifications> educationalQualificationses = new HashSet<EducationalQualifications>(0);

    public EducationLevels() {
    }

	
    public EducationLevels(String educationLevel) {
        this.educationLevel = educationLevel;
    }
    public EducationLevels(String educationLevel, Set<Persons> personses, Set<EducationalQualifications> educationalQualificationses) {
       this.educationLevel = educationLevel;
       this.personses = personses;
       this.educationalQualificationses = educationalQualificationses;
    }
   
    public Short getIdEducationLevel() {
        return this.idEducationLevel;
    }
    
    public void setIdEducationLevel(Short idEducationLevel) {
        this.idEducationLevel = idEducationLevel;
    }
    public String getEducationLevel() {
        return this.educationLevel;
    }
    
    public void setEducationLevel(String educationLevel) {
        this.educationLevel = educationLevel;
    }
    public Set<Persons> getPersonses() {
        return this.personses;
    }
    
    public void setPersonses(Set<Persons> personses) {
        this.personses = personses;
    }
    public Set<EducationalQualifications> getEducationalQualificationses() {
        return this.educationalQualificationses;
    }
    
    public void setEducationalQualificationses(Set<EducationalQualifications> educationalQualificationses) {
        this.educationalQualificationses = educationalQualificationses;
    }




}


