package com.securejobs.domain;
// Generated Feb 7, 2014 3:34:15 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * JobTitles generated by hbm2java
 */
public class JobTitles  implements java.io.Serializable {


     private Short idJobTitles;
     private Sectors sectors;
     private String jobTitle;
     private Set<Persons> personses = new HashSet<Persons>(0);
     private Set<Experiences> experienceses = new HashSet<Experiences>(0);

    public JobTitles() {
    }

    public JobTitles(Sectors sectors, String jobTitle, Set<Persons> personses, Set<Experiences> experienceses) {
       this.sectors = sectors;
       this.jobTitle = jobTitle;
       this.personses = personses;
       this.experienceses = experienceses;
    }
   
    public Short getIdJobTitles() {
        return this.idJobTitles;
    }
    
    public void setIdJobTitles(Short idJobTitles) {
        this.idJobTitles = idJobTitles;
    }
    public Sectors getSectors() {
        return this.sectors;
    }
    
    public void setSectors(Sectors sectors) {
        this.sectors = sectors;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public Set<Persons> getPersonses() {
        return this.personses;
    }
    
    public void setPersonses(Set<Persons> personses) {
        this.personses = personses;
    }
    public Set<Experiences> getExperienceses() {
        return this.experienceses;
    }
    
    public void setExperienceses(Set<Experiences> experienceses) {
        this.experienceses = experienceses;
    }




}


