package com.securejobs.domain;
// Generated Feb 7, 2014 3:34:15 PM by Hibernate Tools 3.6.0



/**
 * Referees generated by hbm2java
 */
public class Referees  implements java.io.Serializable {


     private Integer idReferees;
     private Persons persons;
     private String title;
     private String forename;
     private String surname;
     private String email;
     private String contactPhone;
     private String relationship;
     private Boolean permissionToContact;
     private Boolean permissionToStoreDetails;
     private Boolean verified;
     private String howVerified;
     private byte[] referenceDoc;

    public Referees() {
    }

	
    public Referees(Persons persons, String forename, String surname) {
        this.persons = persons;
        this.forename = forename;
        this.surname = surname;
    }
    public Referees(Persons persons, String title, String forename, String surname, String email, String contactPhone, String relationship, Boolean permissionToContact, Boolean permissionToStoreDetails, Boolean verified, String howVerified, byte[] referenceDoc) {
       this.persons = persons;
       this.title = title;
       this.forename = forename;
       this.surname = surname;
       this.email = email;
       this.contactPhone = contactPhone;
       this.relationship = relationship;
       this.permissionToContact = permissionToContact;
       this.permissionToStoreDetails = permissionToStoreDetails;
       this.verified = verified;
       this.howVerified = howVerified;
       this.referenceDoc = referenceDoc;
    }
   
    public Integer getIdReferees() {
        return this.idReferees;
    }
    
    public void setIdReferees(Integer idReferees) {
        this.idReferees = idReferees;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getForename() {
        return this.forename;
    }
    
    public void setForename(String forename) {
        this.forename = forename;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }
    public Boolean getPermissionToContact() {
        return this.permissionToContact;
    }
    
    public void setPermissionToContact(Boolean permissionToContact) {
        this.permissionToContact = permissionToContact;
    }
    public Boolean getPermissionToStoreDetails() {
        return this.permissionToStoreDetails;
    }
    
    public void setPermissionToStoreDetails(Boolean permissionToStoreDetails) {
        this.permissionToStoreDetails = permissionToStoreDetails;
    }
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }
    public String getHowVerified() {
        return this.howVerified;
    }
    
    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }
    public byte[] getReferenceDoc() {
        return this.referenceDoc;
    }
    
    public void setReferenceDoc(byte[] referenceDoc) {
        this.referenceDoc = referenceDoc;
    }




}


