package com.securejobs.domain;
// Generated Feb 7, 2014 3:34:15 PM by Hibernate Tools 3.6.0



/**
 * Skills generated by hbm2java
 */
public class Skills  implements java.io.Serializable {


     private Integer idSkills;
     private Persons persons;
     private String skillName;
     private String skillLevel;
     private Boolean verified;
     private String howVerified;

    public Skills() {
    }

	
    public Skills(Persons persons, String skillName) {
        this.persons = persons;
        this.skillName = skillName;
    }
    public Skills(Persons persons, String skillName, String skillLevel, Boolean verified, String howVerified) {
       this.persons = persons;
       this.skillName = skillName;
       this.skillLevel = skillLevel;
       this.verified = verified;
       this.howVerified = howVerified;
    }
   
    public Integer getIdSkills() {
        return this.idSkills;
    }
    
    public void setIdSkills(Integer idSkills) {
        this.idSkills = idSkills;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }
    public String getSkillLevel() {
        return this.skillLevel;
    }
    
    public void setSkillLevel(String skillLevel) {
        this.skillLevel = skillLevel;
    }
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }
    public String getHowVerified() {
        return this.howVerified;
    }
    
    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }




}


